### PR TITLE
Fire autocmd on pinned state change

### PR DESCRIPTION
**Pull request by ADIX7**
Execute an autocmd when pinned state changes.

### CODE REVIEW

**Comment by ADIX7** [comment]
(I can't set up my formatting settings for lua, so feel free to reformat with 2 space indenting)

**Comment by al-ce** [comment]
Works for me, both with the direct toggle call and on the Telescope actions, though I don't use early-retirement. I tried it with

```lua
  vim.api.nvim_create_autocmd("User", {
    callback = function(opts)
      vim.notify("Hbac toggled a pin")
    end,
    pattern = "HBACPinned",
  })
```

To fix the formatting, you could run this Vim command in `actions.lua` (the project uses tab indentation)

`:%s/\s\{4\}/\t/g`

or, assuming you have stylua available, from the project root (or prepend a `!` to run it  in Vim) 

`stylua lua/hbac/command/actions.lua --indent-type Tabs`

**Comment by ADIX7** [comment]
I formatted the file!

**Comment by axkirillov** [comment]
Lgtm

**Review by axkirillov — APPROVED** [review]

**Pull request merged**
